version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src:/var/www/html

  web1:
    container_name: web1
    build:
      context: ./docker/web1
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./docker/web1/php.ini:/usr/local/etc/php/php.ini

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306


volumes:
  db-store:


networks:
  default :
